Renovate/all minor [FORK] (#1691)
* chore(deps): update all minor dependencies

* Removed assemblyline_client related code

* Bumping deps; forked from renovate/all-minor

* Bumping up moto from major v1 => v4

* Regened requirements.txt file

* Trying again with a newline at EOF

* Bump up black test dep

* Black format

* Removed unused import

* Sort imports

* Brought in a few mypy types

* chore: formatting

* chore: reformat files (I must not have updated black when i did that last time)

* Downgrade mypy, freeze reqs, reference all-minor utils branch

* Upgrade `flask-bcrypt` to get around error:

Error: While importing 'application', an ImportError was raised:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/workspace/application.py", line 17, in <module>
    from app import create_app
  File "/workspace/app/__init__.py", line 31, in <module>
    from app.encryption import CryptoSigner
  File "/workspace/app/encryption.py", line 3, in <module>
    from flask_bcrypt import check_password_hash, generate_password_hash
  File "/home/vscode/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 21, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/home/vscode/.local/lib/python3.9/site-packages/werkzeug/security.py)

* Update __ident_func__ is referenced due to werkzeug upgrade

Error this solves:
from functools import cached_property, partial
from typing import Optional
import greenlet

from flask import _app_ctx_stack  # type: ignore
from flask_sqlalchemy import BaseQuery, SignallingSession, SQLAlchemy, get_state
from sqlalchemy import orm

class ExplicitRoutingSession(SignallingSession):
    """
    This session implementation will route to explicitly named bind.
    If no bind is mentioned with the session via the `using_bind` function,
    then the `reader` bind will get returned instead.
    """

    _name: Optional[str] = None

    def get_bind(self, mapper=None, clause=None):
        # If reader and writer binds are not configured,
        # connect using the default SQLALCHEMY_DATABASE_URI
        if not self.binds_setup:
            return super().get_bind(mapper, clause)

        return self.load_balance(mapper, clause)

    def load_balance(self, mapper=None, clause=None):
        # Use the explicit name if present
        if self._name and not self._flushing:
            bind = self._name
            self._name = None
            self.app.logger.debug(f"Connecting -> {bind}")
            return get_state(self.app).db.get_engine(self.app, bind=bind)

        # Everything else goes to the writer engine
        else:
            self.app.logger.debug("Connecting -> writer")
            return get_state(self.app).db.get_engine(self.app, bind="writer")

    def using_bind(self, name: str):
        self._name = name
        return self

    @cached_property
    def binds_setup(self):
        binds = self.app.config["SQLALCHEMY_BINDS"] or {}
        return all([k in binds for k in ["reader", "writer"]])

class RoutingSQLAlchemy(SQLAlchemy):
    def on_reader(self):
        return self.session().using_bind("reader")

    def create_scoped_session(self, options=None):
        options = options or {}
        options.setdefault("query_cls", BaseQuery)

        return orm.scoped_session(partial(ExplicitRoutingSession, self, **options), scopefunc=greenlet.getcurrent)

* Downgrade marshmallow, mm-sqlalchemy and environs to get things working

* Give unique names to duplicate blueprints

* Remove unused import

* Add greenlet dep to keep read queries working

* fix mock import

* Skip letter tests

* Change how blueprints are added to work with latest Flask

* Skip missed test.

* Troubleshooting waffles action failure

* Update reference to new utils tag.

* Undo changes to devcontainer's docker-compose

* Undo changes to test.yml workflow

* Bump black back up (mistakenly merged the wrong version)

* Run `make freeze-requirements`

* Fix merge issue.

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Andrew Leith <andrew.leith@cds-snc.ca>